# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains banana testing job
  sonarqube:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Run "danger" script
        run: echo Mock danger

      - name: Run check-git-changes
        run: echo Mock check-git-changes

      - name: Run reconcile-config-check
        run: echo Mock reconcile-config-check

      - name: Run sonarqube
        run: echo Mock sonarqube
        
  root:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Run npm-auth-root-folder
        run: echo Mock npm-auth-root-folder

      - name: Run install-root
        run: echo Mock install-root

      - name: upload-artifact
        run: echo Mock upload-artifact
