# This is a basic workflow to help you get started with Actions

name: Banana Testing CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains banana testing job
  sonarqube:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Run "danger" script
        run: echo Mock danger

      - name: check-git-changes
        run: echo Mock check-git-changes

      - name: reconcile-config-check
        run: echo Mock reconcile-config-check

      - name: sonarqube
        run: echo Mock sonarqube
        
  root:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: npm-auth-root-folder
        run: echo Mock npm-auth-root-folder

      - name: install-root
        run: echo Mock install-root

      - name: make-artifact
        run: |
          echo Mock make-artifact
          mkdir -p path/to/rootArtifact
          echo someRootArtifact > path/to/rootArtifact/rootArtifact.txt
    
      - uses: actions/upload-artifact@master
        with:
          name: root-artifact
          path: path/to/rootArtifact
        
  common:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: npm-auth-common-folder
        run: echo Mock npm-auth-common-folder

      - name: install-common
        run: echo Mock install-root

      - name: make-artifact
        run: |
          echo Mock make-artifact
          mkdir -p path/to/commonArtifact
          echo someCommonArtifact > path/to/commonArtifact/commonArtifact.txt
    
      - uses: actions/upload-artifact@master
        with:
          name: common-artifact
          path: path/to/commonArtifact
        
  main:
    needs: root
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: npm-auth-webapp-folder
        run: echo Mock npm-auth-webapp-folder

      - name: install-webapp
        run: echo Mock install-webapp

      - name: make-artifact
        run: |
          echo Mock make-artifact
          mkdir -p path/to/appArtifact
          echo someAppArtifact > path/to/appArtifact/appArtifact.txt
    
      # upload
      - uses: actions/upload-artifact@master
        with:
          name: app-artifact
          path: path/to/appArtifact

      # download
      - uses: actions/download-artifact@master
        with:
          name: root-artifact
          path: path/to/rootArtifact

      - name: check rootArtifact
        run: cat path/to/rootArtifact/rootArtifact.txt
